// Copyright (c) All contributors. All rights reserved. Licensed under the MIT license.

namespace Kimi.Compiler;

#pragma warning disable SA1402, CS1591 // Stable compiler-owned Kimi catalog vocabulary.

public enum KimiDeclarationId : byte
{
    Copy,
    Owned,
    Callable,
    WriteLine,
    Option,
    Result,
    Array,
    FromEnd,
    ClosedRange,
    ResolvedRange,
    Slice,
    Dictionary,
    Stringify, // Reserved legacy ID; not a declaration or special source identifier.
    Equatable,
    Comparable,
    Iterator,
    IntoIterable,
    ObjectOwnership, // Reserved legacy aggregate ID; no longer a declaration entry.
    Sealed,
    Replace,
    Exchange,
    Swap,
    MakeObj,
    MakeRc,
    MakeArc,
    Clone,
    Downgrade,
    Upgrade,
    MakeRcCyclic,
    MakeArcCyclic,
    Weak,
    TestTempDirectory,
    ArrayReserve,
    ArrayAppend,
    ArrayInsert,
    ArrayPop,
    ArrayRemove,
    ArrayClear,
    ArrayShrinkToFit,
    Utf8Format,
    BufferWriter,
    BufferFull,
    WriteWindow,
    Utf8Writer,
    FixedBuffer,
    HeapBuffer,
    Utf8Slice,
    InvalidUtf8,
    TextFixed,
    TextHeap,
    TextWriter,
    TextUtf8,
    TextValidateUtf8,
    TextToString,
    TextTryFormat,
    TextRelease,
    FixedBufferBytes,
    FixedBufferText,
    FixedBufferValidate,
    FixedBufferClear,
    FixedBufferReserve,
    FixedBufferIntoText,
    HeapBufferBytes,
    HeapBufferText,
    HeapBufferValidate,
    HeapBufferClear,
    HeapBufferReserve,
    HeapBufferIntoString,
    WindowPush,
    WindowAppend,
    WindowLimit,
    WindowCommit,
    WriterWrite,
    WriterStatus,
    WriteLineUtf8,
    ObjectPayload,
    DictionaryReserve,
    DictionaryTryInsert,
    DictionaryInsertOrReplace,
    DictionaryRemove,
    DictionaryTryGet,
    DictionaryClear,
    DictionaryShrinkToFit,
    Indexable,
    UniqIndexable,
    ArraySwap,
    ArrayWithCapacity,
    LendingIterator,
    Iterable,
    UniqIterable,
    RefRemainder,
    UniqRemainder,
    OwnedRemainder,
    StorageBorrowShared,
    StorageBorrowExclusive,
    StorageSplitShared,
    StorageSplitExclusive,
    StorageOwn,
    StorageTakeFirst,
    StorageLend,
    StorageSplit,
    StorageRelease,
    PrimitiveInteger,
    Range,
    DictionaryRefRemainder,
    StorageBorrowDictionary,
    StorageLendKey,
    StorageLendValue,
    DictionaryUniqRemainder,
    StorageBorrowDictionaryExclusive,
    StorageLendUniqKey,
    StorageSplitValue,
    DictionaryOwnedRemainder,
    StorageOwnDictionary,
    StorageKeyAt,
    StorageValueAt,
    StorageBorrowFixedShared,
    StorageBorrowFixedExclusive,
    InlineStorage,
    StorageOwnFixed,
    StorageInlineBase,
    Position,
    PositionRange,
    Start,
    End,
    StorageDictionaryLayout,
    DictionaryIndex,
    DictionaryIndexUniq,
    StorageMissingDictionaryKey,
}

public enum KimiDeclarationState : byte
{
    Missing,
    Invalid,
    Validated,
}

/// <summary>A required identity and its current declaration validation; not runtime availability.</summary>
public readonly record struct KimiDeclaration(KimiDeclarationId Id, string Name, BindingSymbol? Symbol, KimiDeclarationState State);
