// Copyright (c) All contributors. All rights reserved. Licensed under the MIT license.

namespace Kimi.Compiler;

#pragma warning disable SA1402, CS1591 // Compiler-owned identity vocabulary.

public enum IntrinsicKind : byte
{
    None,
    Copy,
    Owned,
    Callable,
    Sealed,
    ObjectPayload,
    PrimitiveInteger,
}

/// <summary>Identifies a compiler-provided language function implementation.</summary>
public enum CompilerFunctionKind : byte
{
    None,
    WriteLine,
    Abort,
    Replace,
    Exchange,
    Swap,
    MakeObj,
    TestTempDirectory,
    ArrayReserve,
    ArrayAppend,
    ArrayInsert,
    ArrayPop,
    ArrayRemove,
    ArrayClear,
    ArrayShrinkToFit,
    ArraySwap,
    ArrayWithCapacity,
    TextFixed,
    TextHeap,
    TextWriter,
    TextUtf8,
    TextValidateUtf8,
    TextToString,
    TextTryFormat,
    TextRelease,
    FixedBufferBytes,
    FixedBufferText,
    FixedBufferValidate,
    FixedBufferClear,
    FixedBufferReserve,
    FixedBufferIntoText,
    HeapBufferBytes,
    HeapBufferText,
    HeapBufferValidate,
    HeapBufferClear,
    HeapBufferReserve,
    HeapBufferIntoString,
    WindowPush,
    WindowAppend,
    WindowLimit,
    WindowCommit,
    WriterWrite,
    WriterStatus,
    WriteLineUtf8,
    BuiltinFormat,
    BuiltinEquals,
    BuiltinCompare,
    StorageBorrowShared,
    StorageBorrowExclusive,
    StorageOwn,
    StorageLend,
    StorageSplit,
    StorageRelease,
    StorageBorrowDictionary,
    StorageLendKey,
    StorageLendValue,
    StorageBorrowDictionaryExclusive,
    StorageLendUniqKey,
    StorageSplitValue,
    StorageOwnDictionary,
    StorageKeyAt,
    StorageValueAt,
    StorageBorrowFixedShared,
    StorageBorrowFixedExclusive,
    StorageOwnFixed,
    StorageInlineBase,
    StorageDictionaryLayout,
    StorageMissingDictionaryKey,
    StoragePlaceDictionaryEntry,
    StoragePlaceDictionaryValue,
    StorageReserveDictionary,
    StorageShrinkDictionary,
}
