# Rebuild the embedded decimal cores from pinned, unchanged Ryu sources (Boost license).
[CmdletBinding()]
param([string] $ToolchainRoot = '')
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'toolchain.ps1')
$toolRoot = Resolve-KimiToolchainRoot $ToolchainRoot
$profile = Read-KimiWindowsProfile
$clang = (Get-KimiLlvmToolIdentity (Join-Path $toolRoot 'clang.exe') $profile.llvmVersion).path
$repo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$vendor = Join-Path $repo 'third_party/ryu'
$build = Join-Path $repo 'bin/ryu'
$include = Join-Path $build 'include'
New-Item -ItemType Directory -Path $include -Force | Out-Null
$headers = @{
    'stdint.h' = @'
#pragma once
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long long uint64_t;
typedef int int32_t;
typedef long long int64_t;
#define UINT32_MAX 4294967295U
'@
    'stdbool.h' = "#pragma once`n#define bool _Bool`n#define true 1`n#define false 0`n"
    'assert.h' = "#pragma once`n#define assert(condition) ((void)0)`n"
    'string.h' = "#pragma once`nvoid *memcpy(void *, const void *, unsigned long long);`n"
}
foreach ($name in $headers.Keys) { [IO.File]::WriteAllText((Join-Path $include $name), $headers[$name]) }
$result = [Text.StringBuilder]::new()
[void]$result.Append("; Generated by backend/windows-x64/generate-ryu.ps1; do not edit.`n; Ryu, Copyright 2018 Ulf Adams; Boost Software License 1.0 (third_party/ryu/LICENSE-Boost).`n")
$declarations = [Collections.Generic.SortedSet[string]]::new([StringComparer]::Ordinal)
foreach ($width in @(32, 64)) {
    $stem = if ($width -eq 32) { 'f2s' } else { 'd2s' }
    $core = if ($width -eq 32) { 'f2d' } else { 'd2d' }
    $source = [IO.File]::ReadAllText((Join-Path $vendor "ryu/$stem.c")).Replace("`r`n", "`n")
    $end = $source.IndexOf('static inline int to_chars(')
    if ($end -lt 0) { throw "Missing upstream core boundary: $stem" }
    $source = $source.Substring(0, $end)
    $source = [regex]::Replace($source, '(?m)^#include "ryu/(?:ryu|digit_table)\.h"\n', '')
    $source = [regex]::Replace($source, '(?m)^#include <(?:stdlib|limits)\.h>\n', '')
    $source += "`nvoid __kimi_ryu$width(uint64_t fraction, uint32_t exponent, uint64_t *mantissa, int32_t *power) {`n"
    $cast = if ($width -eq 32) { '(uint32_t)' } else { '' }
    $source += "  floating_decimal_$width value = $core($cast fraction, exponent);`n  *mantissa = value.mantissa;`n  *power = value.exponent;`n}`n"
    $inputPath = Join-Path $build "$stem.c"
    $irPath = Join-Path $build "$stem.ll"
    [IO.File]::WriteAllText($inputPath, $source)
    # Clang's native 128-bit multiplication lowers to x64 integer instructions. No wide division is used.
    & $clang --target=x86_64-pc-windows-msvc -U_MSC_VER -DRYU_FLOAT_FULL_TABLE -DNDEBUG -nostdinc -I $include -I $vendor -std=c11 -O2 -S -emit-llvm -ffreestanding -fno-builtin -fno-stack-protector -fno-ident -fno-strict-aliasing -fno-discard-value-names -march=x86-64 -mno-avx $inputPath -o $irPath
    if ($LASTEXITCODE -ne 0) { throw "Ryu compilation failed: $stem" }
    $ir = [IO.File]::ReadAllText($irPath).Replace("`r`n", "`n")
    $ir = [regex]::Replace($ir, '@([A-Za-z_][A-Za-z_0-9.]*)', {
        param($match)
        $name = $match.Groups[1].Value
        if ($name.StartsWith('llvm.') -or $name -ceq "__kimi_ryu$width") { return $match.Value }
        return "@__kimi_ryu${width}_$name"
    })
    foreach ($line in $ir.Split("`n")) {
        if ($line -match '^(?:;|source_filename|target |attributes |!)') { continue }
        $line = [regex]::Replace($line, ', ![A-Za-z0-9_.]+ ![0-9]+', '')
        if ($line.StartsWith('declare ')) {
            if ($line -notmatch '@llvm\.') { throw "Unexpected runtime dependency: $line" }
            [void]$declarations.Add([regex]::Replace($line, ' #[0-9]+', ''))
            continue
        }
        if ($line.StartsWith('define ')) {
            $line = $line.Replace('define dso_local ', 'define internal ')
            $line = [regex]::Replace($line, '#[0-9]+', '#0')
        }
        [void]$result.Append($line).Append("`n")
    }
}
foreach ($declaration in $declarations) { [void]$result.Append($declaration).Append("`n") }
$outputPath = Join-Path $repo 'Kimi/Compiler/Emission/Utf8FloatRyu.ll.in'
[IO.File]::WriteAllText($outputPath, $result.ToString())
Write-Host "Generated $outputPath"
