<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>

    <PackageId>Kimigayo</PackageId>
    <Authors>archi-Doc</Authors>
    <Product>Kimigayo</Product>
    <Description>Work in Process</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/archi-Doc/Kimigayo</PackageProjectUrl>
    <RepositoryUrl>https://github.com/archi-Doc/Kimigayo</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Misc\Language\strings-en.tinyhand" />
    <None Remove="Misc\Language\strings-ja.tinyhand" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Generated\*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Diagnostics\DiagnosticCode.tinyhand" />
    <EmbeddedResource Include="Misc\Language\strings-en.tinyhand" />
    <EmbeddedResource Include="Misc\Language\strings-ja.tinyhand" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Arc.Collections" Version="1.42.0" />
    <PackageReference Include="Arc.Threading" Version="0.50.0" />
    <PackageReference Include="Arc.Unit" Version="0.43.0" />
    <PackageReference Include="SimpleCommandLine" Version="0.42.0" />
    <PackageReference Include="SimplePrompt" Version="0.22.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Tinyhand" Version="0.143.2" />
    <PackageReference Include="ValueLink" Version="0.117.0" />
  </ItemGroup>

</Project>
