"""Generate pinned Unicode 15.0 identifier and normalization tables from the UCD."""

import hashlib
import pathlib
import sys

source = pathlib.Path(sys.argv[1])
target = pathlib.Path(__file__).resolve().parents[1] / "Kimi/Compiler/Helper/UnicodeIdentifierData.cs"
properties = [0] * 0x110000
decompositions = {}
excluded = set()
ucd = (source / "UnicodeData.txt").read_bytes()
normalization = (source / "DerivedNormalizationProps.txt").read_bytes()
assert b"DerivedNormalizationProps-15.0.0.txt" in normalization
first = None
for line in ucd.decode().splitlines():
    fields = line.split(";")
    code = int(fields[0], 16)
    category = fields[2]
    flags = 3 if category in {"Lu", "Ll", "Lt", "Lm", "Lo", "Nl"} else 2 if category in {"Mn", "Mc", "Nd", "Pc"} else 0
    value = flags | (int(fields[3]) << 2) | (4096 if category == "Lu" else 0)
    if fields[1].endswith(", First>"):
        first = code
    elif fields[1].endswith(", Last>"):
        properties[first:code + 1] = [value] * (code - first + 1)
    else:
        properties[code] = value
    if fields[5] and not fields[5].startswith("<"):
        decompositions[code] = [int(x, 16) for x in fields[5].split()]

for line in normalization.decode().splitlines():
    fields = [x.strip() for x in line.split("#")[0].split(";")]
    if len(fields) < 2 or not fields[0]:
        continue
    bounds = [int(x, 16) for x in fields[0].split("..")]
    codes = range(bounds[0], bounds[-1] + 1)
    if fields[1] == "Full_Composition_Exclusion":
        excluded.update(codes)
    if fields[1] == "NFC_QC":
        for code in codes:
            properties[code] |= 1024 if fields[2] == "N" else 2048

ranges = []
start = 0
for code in range(1, len(properties) + 1):
    if code == len(properties) or properties[code] != properties[start]:
        if properties[start]:
            ranges.extend([start, code - 1, properties[start]])
        start = code
decomp = []
composition = []
for code, parts in sorted(decompositions.items()):
    assert len(parts) <= 2
    decomp.extend([code, parts[0], parts[1] if len(parts) == 2 else 0])
    if len(parts) == 2 and code not in excluded:
        composition.append((parts[0] << 42) | (parts[1] << 21) | code)

with target.open("w", encoding="utf-8", newline="\n") as out:
    out.write("// <auto-generated/>\n// Unicode 15.0.0, https://www.unicode.org/Public/15.0.0/ucd/\n")
    out.write("// Unicode data license: https://www.unicode.org/license.txt\n")
    out.write(f"// UnicodeData.txt SHA-256: {hashlib.sha256(ucd).hexdigest()}\n")
    out.write(f"// DerivedNormalizationProps.txt SHA-256: {hashlib.sha256(normalization).hexdigest()}\n")
    out.write("namespace Kimi.Compiler.Helper;\n\ninternal static class UnicodeIdentifierData\n{\n")
    for name, data, kind in [("Properties", ranges, "uint"), ("Decompositions", decomp, "uint"), ("Compositions", sorted(composition), "ulong")]:
        out.write(f"    internal static ReadOnlySpan<{kind}> {name} =>\n    [\n")
        for index in range(0, len(data), 9):
            out.write("        " + ", ".join(f"0x{x:X}" + ("UL" if kind == "ulong" else "") for x in data[index:index + 9]) + ",\n")
        out.write("    ];\n")
    out.write("}\n")
print(target)
