param([Parameter(Mandatory = $true)][string]$UnicodeDataPath)

$ErrorActionPreference = 'Stop'
$expected = '806E9AED65037197F1EC85E12BE6E8CD870FC5608B4DE0FFFD990F689F376A73'
if ((Get-FileHash -LiteralPath $UnicodeDataPath -Algorithm SHA256).Hash -ne $expected) {
    throw 'Expected the unmodified Unicode 15.0.0 UnicodeData.txt.'
}

$ranges = [System.Collections.Generic.List[int]]::new()
$rangeStart = -1
$rangeEnd = -1
foreach ($line in [IO.File]::ReadLines((Resolve-Path -LiteralPath $UnicodeDataPath))) {
    $fields = $line.Split(';')
    if ($fields[2][0] -notin @('P', 'S')) { continue }
    $scalar = [Convert]::ToInt32($fields[0], 16)
    if ($scalar -eq $rangeEnd + 1 -and $rangeStart -ge 0) { $rangeEnd = $scalar; continue }
    if ($rangeStart -ge 0) { $ranges.Add($rangeStart); $ranges.Add($rangeEnd) }
    $rangeStart = $rangeEnd = $scalar
}
if ($rangeStart -ge 0) { $ranges.Add($rangeStart); $ranges.Add($rangeEnd) }
$output = [Text.StringBuilder]::new()
[void]$output.AppendLine('// <auto-generated/>')
[void]$output.AppendLine('// Unicode 15.0.0: https://www.unicode.org/Public/15.0.0/ucd/UnicodeData.txt')
[void]$output.AppendLine('// Unicode data license: https://www.unicode.org/license.txt')
[void]$output.AppendLine("// SHA-256: $expected")
[void]$output.AppendLine('// Generated by GenerateMarkdownUnicode.ps1; P* and S* categories, merged inclusive ranges.')
[void]$output.AppendLine('namespace Kimi.Compiler.Documentation;')
[void]$output.AppendLine('internal static class MarkdownUnicodeData')
[void]$output.AppendLine('{')
[void]$output.AppendLine('    internal static ReadOnlySpan<int> Punctuation =>')
[void]$output.AppendLine('    [')
for ($i = 0; $i -lt $ranges.Count; $i += 8) {
    $entries = for ($j = $i; $j -lt [Math]::Min($i + 8, $ranges.Count); $j++) { '0x{0:X}' -f $ranges[$j] }
    [void]$output.AppendLine('        ' + ($entries -join ', ') + ',')
}
[void]$output.AppendLine('    ];')
[void]$output.AppendLine('}')
$targetPath = Join-Path $PSScriptRoot 'MarkdownUnicodeData.cs'
[IO.File]::WriteAllText($targetPath, $output.ToString().Replace("`r`n", "`n"), [Text.UTF8Encoding]::new($false))
Write-Output "Generated $($ranges.Count / 2) punctuation/symbol ranges."
